### ISSUE TITLE
installation of Nominatim 3.7 failed at OSM import step (Signals.SIGBUS)

### ISSUE THREAD

**Issue by vinhdizzo** [mediagis/nominatim-docker#254]
**Describe the bug**
Installation of Nominatim 3.7 failed at OSM import step.

**To Reproduce**
1. Use command:
```
docker run -it --rm --shm-size=2g -e THREADS=4 -e POSTGRES_SHARED_BUFFERS=1GB -e POSTGRES_MAINTAINENCE_WORK_MEM=1GB -e POSTGRES_AUTOVACUUM_WORK_MEM=1GB -e POSTGRES_WORK_MEM=50MB -e POSTGRES_EFFECTIVE_CACHE_SIZE=1GB -e POSTGRES_SYNCHRONOUS_COMMIT=off -e POSTGRES_MAX_WAL_SIZE=1GB -e POSTGRES_CHECKPOINT_TIMEOUT=10min -e POSTGRES_CHECKPOINT_COMPLETITION_TARGET=0.9 -e IMPORT_STYLE=address -e PBF_PATH=/nominatim/data/us-latest.osm.pbf -e REPLICATION_URL=http://download.geofabrik.de/north-america/us-updates/ -v ~/Downloads/osm-data:/nominatim/data -e IMPORT_WIKIPEDIA=false -v nominatim_pgdata:/var/lib/postgresql/12/main -v  ~/Downloads/nominatim-flatnode:/nominatim/flatnode -e NOMINATIM_FLATNODE_FILE=/nominatim/flatnode/flatnode.file -p 8080:8080 --name nominatim mediagis/nominatim:3.7
```
I obtained the postgres tuning info [here](https://github.com/mediagis/nominatim-docker/issues/237#issuecomment-860353095) as I am on a laptop with 16GB memory.  I have to go the flatnode approach because I kept getting an error that I was running out of space, which is weird because I had 200GB to start.  With flatnode, the file generated was about 70GB.

2. See error
```
+ sudo -E -u nominatim nominatim import --osm-file /nominatim/data/us-latest.osm.pbf --threads 4
2021-08-31 02:08:47: Using project directory: /nominatim
2021-08-31 02:08:47: Creating database
2021-08-31 02:08:47: Setting up database
2021-08-31 02:08:48: Loading basic data
2021-08-31 02:08:50: Installing database module
2021-08-31 02:08:50: Importing OSM data file
2021-08-31 02:08:50  osm2pgsql version 1.4.1
2021-08-31 02:08:50  Database version: 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)
2021-08-31 02:08:50  PostGIS version: 3.0
2021-08-31 02:08:50  Parsing gazetteer style file '/usr/local/etc/nominatim/import-full.style'.
NOTICE:  table "place" does not exist, skipping
Processing: Node(1017335k 623.0k/s) Way(247k 0.12k/s) Relation(0 0.0/s)
Processing: Node(1017335k 623.0k/s) Way(462k 0.14k/s) Relation(0 0.0/s)Get-Date
Processing: Node(1017335k 623.0k/s) Way(666k 0.14k/s) Relation(0 0.0/s)
Processing: Node(1017335k 623.0k/s) Way(2462k 0.19k/s) Relation(0 0.0/s)Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 77, in run
    database_import.import_osm_data(Path(args.osm_file),
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 165, in import_osm_data
    run_osm2pgsql(options)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 131, in run_osm2pgsql
    subprocess.run(cmd, cwd=options.get('cwd', '.'), env=env, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/lib/nominatim/osm2pgsql', '--hstore', '--latlon', '--slim', '--with-forward-dependencies', 'false', '--log-progress', 'true', '--number-processes', '1', '--cache', '0', '--output', 'gazetteer', '--style', '/usr/local/etc/nominatim/import-full.style', '--create', '--flat-nodes', '/nominatim/flatnode/flatnode.file', '/nominatim/data/us-latest.osm.pbf']' died with <Signals.SIGBUS: 7>.
```

**Expected behavior**
Install successfully.  Error occurred as I let the installation run through the night, so happened sometime before the 10 hour mark.

**Desktop / Server (please complete the following information):**
 - OS & Version: Windows 10
 - Docker Version: Docker version 19.03.4, build 9013bf5 
 - Nominatim Version: [e.g. 3.7.0]

**Comment by mtmail** [comment]
The "Processing: Node(1017335k 623.0k/s) Way(2462k 0.19k/s) Relation(0 0.0/s)" lines come from [osm2pgsql](https://osm2pgsql.org/). The amount of data for the whole United States`us-latest.osm.pbf` is too large for 16GB memory. 32GB might work. https://www.nominatim.org/release-docs/latest/admin/Installation/#hardware advises 64GB for the whole planet as minimum.

> I was running out of space, which is weird because I had 200GB to start

I think 200GB disc space will not be enough to import the whole United States. I don't have any specific number what disc space is required for this import either though.

> With flatnode, the file generated was about 70GB.

That's the expected size. It won't grow much larger.

**Comment by vinhdizzo** [comment]
Thanks for your response, @mtmail!  I thought that 200GB should be sufficient for the US since the whole planet requires 900GB.  Moreover, I typically monitor disk usage throughout the install / import process, and I always have at least 110GB of disk space free after the flatnode file has been created.  There was no sign of the disk getting full.

I just tried re-doing the installation with the US West region, and after less than a day of import, I now get this error:

```
2021-09-01 08:47:25: Done 12041/12041 in 19 @ 606.918 per second - FINISHED postcodes (location_postcode)

2021-09-01 08:50:15: Post-process tables
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 133, in run
    database_import.create_search_indices(conn, args.config,
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 308, in create_search_indices
    sql.run_sql_file(conn, 'indices.sql', drop=drop)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/sql_preprocessor.py", line 103, in run_sql_file
    cur.execute(sql)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 26, in execute
    super().execute(query, args)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

Do you still think I'm running out of disk space?  I ran the same command as before, but pointing to the new smaller region.

I will try again now with just a single state.  Thanks!

**Comment by mtmail** [comment]
Check the logfile of the Postgresql server. It might give a hint why it (the Postgresql server) crashed. If the database on another machine it could also be a network interruption issue.

**Comment by vinhdizzo** [comment]
I'm relatively new to docker.  How do I inspect the log after the container has closed out (when the installation failed)?  I haven't had success in viewing files on the container or image.  Appreciate your assistance!

**Comment by vinhdizzo** [comment]
I got the same error on the california file.  I will try again with the socal file.  I've also mounted `/var/log` on the container to a host folder.  That way I could inspect the postgres log if the installation fails.  Will let you know what I find.  Thanks.

**Comment by vinhdizzo** [comment]
I just re-ran with the socal pbf file, which is a lot smaller than what I started.  I got the same error as my original post.  The postgreSQL log shows:

```
2021-09-01 21:40:40.877 UTC [55] LOG:  starting PostgreSQL 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-09-01 21:40:40.877 UTC [55] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-09-01 21:40:40.877 UTC [55] LOG:  listening on IPv6 address "::", port 5432
2021-09-01 21:40:40.877 UTC [55] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-09-01 21:40:40.908 UTC [56] LOG:  database system was shut down at 2021-07-21 12:22:42 UTC
2021-09-01 21:40:40.913 UTC [55] LOG:  database system is ready to accept connections
2021-09-02 01:21:36.083 UTC [184] nominatim@nominatim LOG:  incomplete message from client
2021-09-02 01:21:36.083 UTC [184] nominatim@nominatim CONTEXT:  COPY planet_osm_ways, line 5656292
2021-09-02 01:21:36.083 UTC [184] nominatim@nominatim STATEMENT:  COPY "planet_osm_ways" FROM STDIN
2021-09-02 01:21:36.083 UTC [187] nominatim@nominatim LOG:  incomplete message from client
2021-09-02 01:21:36.083 UTC [187] nominatim@nominatim CONTEXT:  COPY place, line 2223239
2021-09-02 01:21:36.083 UTC [187] nominatim@nominatim STATEMENT:  COPY "place" FROM STDIN
2021-09-02 01:21:36.264 UTC [184] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2021-09-02 01:21:36.264 UTC [184] nominatim@nominatim CONTEXT:  COPY planet_osm_ways, line 5656292
2021-09-02 01:21:36.264 UTC [184] nominatim@nominatim STATEMENT:  COPY "planet_osm_ways" FROM STDIN
2021-09-02 01:21:36.264 UTC [187] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2021-09-02 01:21:36.264 UTC [187] nominatim@nominatim CONTEXT:  COPY place, line 2223239
2021-09-02 01:21:36.264 UTC [187] nominatim@nominatim STATEMENT:  COPY "place" FROM STDIN
2021-09-02 01:21:36.269 UTC [184] nominatim@nominatim LOG:  could not send data to client: Broken pipe
2021-09-02 01:21:36.269 UTC [184] nominatim@nominatim STATEMENT:  COPY "planet_osm_ways" FROM STDIN
2021-09-02 01:21:36.269 UTC [187] nominatim@nominatim LOG:  could not send data to client: Broken pipe
2021-09-02 01:21:36.269 UTC [187] nominatim@nominatim STATEMENT:  COPY "place" FROM STDIN
2021-09-02 01:21:36.274 UTC [184] nominatim@nominatim FATAL:  terminating connection because protocol synchronization was lost
2021-09-02 01:21:36.274 UTC [187] nominatim@nominatim FATAL:  terminating connection because protocol synchronization was lost
```

Any ideas on what is going on?  Am I running out of memory (what's allocated for docker)?

**Comment by vinhdizzo** [comment]
I'm now getting the following error with the re-run:

```
+ sudo -E -u nominatim nominatim replication --init
2021-09-02 06:45:41: Using project directory: /nominatim
2021-09-02 06:45:42: Initialising replication updates
2021-09-02 06:45:47: Updates intialised at sequence 1018 (2021-08-31 15:22:14+00:00)
2021-09-02 06:45:47: Create functions
+ sudo service postgresql stop
 * Stopping PostgreSQL 12 database server                                                                        [ OK ]
+ rm /etc/postgresql/12/main/conf.d/postgres-import.conf
+ echo 'Deleting downloaded dumps in /nominatim'
Deleting downloaded dumps in /nominatim
+ rm -f '/nominatim/*sql.gz'
+ '[' '' '!=' '' ']'
+ touch /var/lib/postgresql/12/main/import-finished
+ cd /nominatim
+ nominatim refresh --website
2021-09-02 06:45:53: Using project directory: /nominatim
2021-09-02 06:45:53: Setting up website directory at /nominatim/website
+ service postgresql start
 * Starting PostgreSQL 12 database server                                                                        [ OK ]
+ service apache2 start
 * Starting Apache httpd web server apache2                                                                              *
 * The apache2 configtest failed.
Output of config test was:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
AH00014: Configuration check failed
Action 'configtest' failed.
The Apache error log may have more information.
```

I did not see a an `apache2` log folder in the folder that I mounted `/var/log` to.  Hmm...

**Comment by vinhdizzo** [comment]
Thanks @leonardehrenfried , it's returning

```
[{"place_id":1404212,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":13347384,"boundingbox":["33.6307333","33.6313663","-117.633312","-117.6311185"],"lat":"33.6309708","lon":"-117.6324265","display_name":"Springfield, Canyon Crest, Mission Viejo, Orange County, 92692, United States","place_rank":26,"category":"highway","type":"residential","importance":0.19999999999999998},{"place_id":1404692,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":13347386,"boundingbox":["33.6959562","33.6962003","-117.7740839","-117.7738424"],"lat":"33.6959562","lon":"-117.7740839","display_name":"Springfield, Heritage Park Apartments, El Camino Real, Irvine, Orange County, 92604, United States","place_rank":26,"category":"highway","type":"residential","importance":0.19999999999999998}]
```

**Comment by leonardehrenfried** [comment]
You get a Springfield in Orange County. Is this what you expect?

**Comment by vinhdizzo** [comment]
Well, I only imported the socal database, so yes :)

**Comment by philipkozeny** [comment]
> I'm now getting the following error with the re-run:
> 
> ```
> + sudo -E -u nominatim nominatim replication --init
> 2021-09-02 06:45:41: Using project directory: /nominatim
> 2021-09-02 06:45:42: Initialising replication updates
> 2021-09-02 06:45:47: Updates intialised at sequence 1018 (2021-08-31 15:22:14+00:00)
> 2021-09-02 06:45:47: Create functions
> + sudo service postgresql stop
>  * Stopping PostgreSQL 12 database server                                                                        [ OK ]
> + rm /etc/postgresql/12/main/conf.d/postgres-import.conf
> + echo 'Deleting downloaded dumps in /nominatim'
> Deleting downloaded dumps in /nominatim
> + rm -f '/nominatim/*sql.gz'
> + '[' '' '!=' '' ']'
> + touch /var/lib/postgresql/12/main/import-finished
> + cd /nominatim
> + nominatim refresh --website
> 2021-09-02 06:45:53: Using project directory: /nominatim
> 2021-09-02 06:45:53: Setting up website directory at /nominatim/website
> + service postgresql start
>  * Starting PostgreSQL 12 database server                                                                        [ OK ]
> + service apache2 start
>  * Starting Apache httpd web server apache2                                                                              *
>  * The apache2 configtest failed.
> Output of config test was:
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
> (2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
> AH00014: Configuration check failed
> Action 'configtest' failed.
> The Apache error log may have more information.
> ```
> 
> I did not see a an `apache2` log folder in the folder that I mounted `/var/log` to. Hmm...

Thats not a problem with the import, just a config from apache since we don't set a server name in the config, so everything should be fine and work.

Did you try it again with a bigger source file?

**Comment by vinhdizzo** [comment]
@philipkozeny I was able to re-run the `docker run` command but without mounting `/var/log`  mapping argument and the server successfully launched.

Since the installation with the Southern California file was successfully, I checked my disk usage and I still have about the same amount left when as when the installation failed for the California, US West, and US map files.  I figure the installation must not be failing because of not having enough free space.  After some exploration, I realize that Docker Engine on Windows has about 2048MB of memory and 1024MB of swap dedicated to it.  I increased them to 6144MB and 2048MB, respectively, and was able to successfully install the California and US West files.  For the US file, I'm sure if I increase these two parameters, then it would also install fine.

I'm reporting this here as others may be running into the same installation issues on their regular desktop or laptop, and increasing the resources allocated to the Docker Engine would resolve these errors.  Thank you!

**Comment by leonardehrenfried** [comment]
BTW, @vinhdizzo we get quite a few issues where people say that they cannot import all the data they need because their machine doesn't have the required resources.

- #207 
- #237 
- #252

Right now we use the nominatim defaults which assume that you have 32GB of ram.

We have some documentation about how to tune the database to use less memory but there are no real world examples for how to use them for a given machine. I think the best solution would be a separate doc page where we collect example commands for various RAM configs and country extracts.

Would you be interested in contributing this?

**Comment by rkakade2021** [comment]
> @philipkozeny I was able to re-run the `docker run` command but without mounting `/var/log` mapping argument and the server successfully launched.
> 
> Since the installation with the Southern California file was successfully, I checked my disk usage and I still have about the same amount left when as when the installation failed for the California, US West, and US map files. I figure the installation must not be failing because of not having enough free space. After some exploration, I realize that Docker Engine on Windows has about 2048MB of memory and 1024MB of swap dedicated to it. I increased them to 6144MB and 2048MB, respectively, and was able to successfully install the California and US West files. For the US file, I'm sure if I increase these two parameters, then it would also install fine.
> 
> I'm reporting this here as others may be running into the same installation issues on their regular desktop or laptop, and increasing the resources allocated to the Docker Engine would resolve these errors. Thank you!

@vinhdizzo - I am new to using Docker too. How should I go about changing the memory allocation for the Docker engine? I am attempting to do that in Windows 10.
