### ISSUE TITLE
Importing fails when IMPORT_WIKIPEDIA=true

### ISSUE THREAD

**Issue by norcis** [mediagis/nominatim-docker#271]
Using CIVO k3s cluster for testing.

2021-11-27 16:11:29: Importing wikipedia importance data
--
2021-11-27 18:11:30 | Traceback (most recent call last):
2021-11-27 18:11:30 | File "/usr/local/bin/nominatim", line 11, in <module>
2021-11-27 18:11:30 | exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
2021-11-27 18:11:30 | File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
2021-11-27 18:11:30 | return parser.run(**kwargs)
2021-11-27 18:11:30 | File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
2021-11-27 18:11:30 | return args.command.run(args)
2021-11-27 18:11:30 | File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 103, in run
2021-11-27 18:11:30 | if refresh.import_wikipedia_articles(args.config.get_libpq_dsn(),
2021-11-27 18:11:30 | File "/usr/local/lib/nominatim/lib-python/nominatim/tools/refresh.py", line 139, in import_wikipedia_articles
2021-11-27 18:11:30 | execute_file(dsn, datafile, ignore_errors=ignore_errors,
2021-11-27 18:11:30 | File "/usr/local/lib/nominatim/lib-python/nominatim/db/utils.py", line 47, in execute_file
2021-11-27 18:11:30 | remain = _pipe_to_proc(proc, fdesc)
2021-11-27 18:11:30 | File "/usr/local/lib/nominatim/lib-python/nominatim/db/utils.py", line 14, in _pipe_to_proc
2021-11-27 18:11:30 | chunk = fdesc.read(2048)
2021-11-27 18:11:30 | File "/usr/lib/python3.8/gzip.py", line 292, in read
2021-11-27 18:11:30 | return self._buffer.read(size)
2021-11-27 18:11:30 | File "/usr/lib/python3.8/_compression.py", line 68, in readinto
2021-11-27 18:11:30 | data = self.read(len(byte_view))
2021-11-27 18:11:30 | File "/usr/lib/python3.8/gzip.py", line 479, in read
2021-11-27 18:11:30 | if not self._read_gzip_header():
2021-11-27 18:11:30 | File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
2021-11-27 18:11:30 | raise BadGzipFile('Not a gzipped file (%r)' % magic)
2021-11-27 18:11:30 | gzip.BadGzipFile: Not a gzipped file (b'<h')

**Comment by leonardehrenfried** [comment]
To me it looks like the wikipedia dump file is corrupted during download.

Can you download it yourself and check that you can unpack it?

**Comment by norcis** [comment]
Seems pod downloads it, but can't unpack.

2021-11-29 07:11:46 | + echo 'Downloading Wikipedia importance dump'
2021-11-29 07:11:46 | + curl https://www.nominatim.org/data/wikimedia-importance.sql.gz -o /nominatim/wikimedia-importance.sql.gz
2021-11-29 07:11:46 | % Total % Received % Xferd Average Speed Time Time Time Current
2021-11-29 07:11:46 | Dload Upload Total Spent Left Speed
2021-11-29 07:11:46 | 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 169 100 169 0 0 816 0 --:--:-- --:--:-- --:--:-- 816
2021-11-29 07:11:46 | + '[' '' = true ']'

**Comment by leonardehrenfried** [comment]
Ah, I just checked it. The file has moved and the URL returns a redirect. `curl` doesn't follow it because the `-L` option isn't set.

Would you like to contribute a fix for that?
