### ISSUE TITLE
Replication Woes

### ISSUE THREAD

**Issue by OmaJDooks** [mediagis/nominatim-docker#315]
let's start with I'm stubborn..first nominatim....and I like to use .yml

This is probably horribly wrong...but it is working && A for effort at minimum
-----------------------------------------------------------------------------------------------------------------------------------------------
version: "2.1"

services:
    nominatim-api:
        environment:
            - PBF_URL=https://ftpmirror.your.org/pub/openstreetmap/pbf/planet-171204.osm.pbf
            - REPLICATION_URL=https://ftpmirror.your.org/pub/openstreetmap/replication/day/
            - IMPORT_WIKIPEDIA=true
            - IMPORT_US_POSTCODES=true
            - IMPORT_GB_POSTCODES=true
            - IMPORT_TIGER_ADDRESSES=true
            - NOMINATIM_PASSWORD=YourStrongRootPasswordHere!
            - IMPORT_STYLE=address
            - THREADS=32
            - NOMINATIM_FLATNODE_FILE=/nominatim/flatnode
        shm_size: '64g'
        image: mediagis/nominatim:4.0
        ports:
            - "8080:8080"
        volumes:
            - nominatim-data-gb:/var/lib/postgresql/12/main
volumes:
    nominatim-data-gb:
        external: true
        name: nominatim-data-gb
        ----------------------------------------------------------------------------------------------------------------------------------------------
        1- I did not set a restart variable
        2-When I try to set replication --this happens--

                                        NAMES
164d8a489dff   0815flo/swifttileservercache:2.1.0-beta                                       "./SwiftTileserverCa…"   12 hours ago   Up 12 hours   0.0.0.0:9000->9000/tcp, :::9000->9000/tcp                                              tileserver-cache
c21ce27273ee   maptiler/tileserver-gl:latest                                                 "/app/docker-entrypo…"   12 hours ago   Up 12 hours   80/tcp                                                                                 tileserver
6f39431c5db0   docker.pkg.github.com/realdevicemap/realdevicemap/realdevicemap:development   "./RealDeviceMapApp"     32 hours ago   Up 32 hours   0.0.0.0:4848->4848/tcp, :::4848->4848/tcp, 0.0.0.0:4949->4949/tcp, :::4949->4949/tcp   SHINYMADNESS
dc5e054dcae8   mediagis/nominatim:4.0                                                        "/bin/sh -c /app/sta…"   33 hours ago   Up 33 hours   5432/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                    nom_nominatim-api_1
entroflux on ugotfluxxed.lol in ~
$ docker exec -it nominatim sudo -u nominatim nominatim replication --project-dir /nominatim  
Error response from daemon: Container 8a2550e7063c398fd1b2ac344c9be6f8d8e76d8d0836c36c9f609806924fb615 is not running
entroflux on ugotfluxxed.lol in ~
$ docker exec -it dc5e054dcae8 sudo -u nominatim nominatim replication --project-dir /nominatim             
2022-04-04 13:32:29: Using project directory: /nominatim
2022-04-04 13:32:42  osm2pgsql version 1.5.1
2022-04-04 13:32:42  Database version: 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
2022-04-04 13:32:42  PostGIS version: 3.0
2022-04-04 13:32:42  ERROR: You seem to not have a nodes table. Did you forget the --flat-nodes option?
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 235, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 96, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 187, in run
    UpdateReplication._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 144, in _update
    state = replication.update(conn, params)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/replication.py", line 119, in update
    run_osm2pgsql(options)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 139, in run_osm2pgsql
    subprocess.run(cmd, cwd=options.get('cwd', '.'),
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/lib/nominatim/osm2pgsql', '--hstore', '--latlon', '--slim', '--with-forward-dependencies', 'false', '--log-progress', 'true', '--number-processes', '1', '--cache', '2000', '--output', 'gazetteer', '--style', '/usr/local/etc/nominatim/import-address.style', '--append', '/nominatim/osmosischange.osc']' returned non-zero exit status 1.
entroflux on ugotfluxxed.lol in ~
$

--------------------------------------------------------------------------------------------------------------------------------------------

Not Feeling it...but if smarter to nuke it and start over..all good...some guidance would be lovely

**Comment by leonardehrenfried** [comment]
The error message says:

```
2022-04-04 13:32:42 ERROR: You seem to not have a nodes table. Did you forget the --flat-nodes option?
Traceback (most recent call last):
```

It appears that you haven't made `/nominatim/flatnode` a volume. This is actually required to use this feature. I advise that you re-read https://github.com/mediagis/nominatim-docker/tree/master/4.0#flatnode-files

**Comment by leonardehrenfried** [comment]
I'm going to close this as there is no activity anymore. If you still have a question, please reopen.
