### ISSUE TITLE
ERROR: std::bad_alloc

### ISSUE THREAD

**Issue by thedmdim** [mediagis/nominatim-docker#337]
I run container as:

```
docker run -t --shm-size=1g \
  -e PBF_URL=https://download.geofabrik.de/europe-latest.osm.pbf \
  -e REPLICATION_URL=https://download.geofabrik.de/europe-updates/ \
  -v nominatim-data:/var/lib/postgresql/12/main \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.0
```

i have 30gb free ram and 1.5tb storage

Running this command after a while i get 
```
chown -R nominatim:nominatim /nominatim
+ cd /nominatim
+ sudo -E -u nominatim nominatim import --osm-file /nominatim/data.osm.pbf --threads 16
2022-06-30 18:25:52: Using project directory: /nominatim
2022-06-30 18:25:52: Creating database
2022-06-30 18:25:54: Setting up country tables
2022-06-30 18:25:56: Importing OSM data file
2022-06-30 18:25:56  osm2pgsql version 1.5.1
2022-06-30 18:25:56  Database version: 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
2022-06-30 18:25:56  PostGIS version: 3.0
2022-06-30 18:25:56  Parsing gazetteer style file '/usr/local/etc/nominatim/import-full.style'.
NOTICE:  table "place" does not exist, skipping
Processing: Node(2609780k 532.1k/s) Way(0k 0.00k/s) Relation(0 0.0/s)2022-06-30 19:47:52  ERROR: std::bad_alloc
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 235, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 96, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 77, in run
    database_import.import_osm_data(files,
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 98, in import_osm_data
    run_osm2pgsql(options)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 139, in run_osm2pgsql
    subprocess.run(cmd, cwd=options.get('cwd', '.'),
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/lib/nominatim/osm2pgsql', '--hstore', '--latlon', '--slim', '--with-forward-dependencies', 'false', '--log-progress', 'true', '--number-processes', '1', '--cache', '44642', '--output', 'gazetteer', '--style', '/usr/local/etc/nominatim/import-full.style', '--create', '/nominatim/data.osm.pbf']' returned non-zero exit status 1.
```

How can I make it working?

**Comment by mtmail** [comment]
The system runs out of memory. Increase the `shm-size` and use a flatnode file. See the documentation on https://github.com/mediagis/nominatim-docker/tree/master/4.0 which mentions Europe.
