### ISSUE TITLE
After Rank 30 suddenly memory get eaten - Server crash

### ISSUE THREAD

**Issue by ChaosEmpire** [mediagis/nominatim-docker#387]
I imported last night germany.osm.pbf
this morning i saw, rank 30 finished (it crashed there with 4.0) so i was really happy
wondering it was at rank 0
finished things like postcodes
and then started a post processing
in that moment 32gb ram got fully eaten and server crashed
i had around 16gb ram free the whole time, i assume, some defaults are not perfect
used the example to import from the github page (without flatnode)

2022-11-08T10:36:49.731584339Z 2022-11-08 10:36:49: Done 7560 in 10 @ 745.161 per second - postcodes (location_postcode) ETA (seconds                                                                       ): 2.77
2022-11-08T10:36:51.733068636Z 2022-11-08 10:36:51: Done 8320 in 12 @ 684.944 per second - postcodes (location_postcode) ETA (seconds                                                                       ): 1.91
2022-11-08T10:36:52.247889588Z 2022-11-08 10:36:52: Done 9000 in 12 @ 710.789 per second - postcodes (location_postcode) ETA (seconds                                                                       ): 0.88
2022-11-08T10:36:52.382386520Z 2022-11-08 10:36:52: Done 9626/9626 in 12 @ 752.251 per second - FINISHED postcodes (location_postcode                                                                       )
2022-11-08T10:36:52.382606622Z
2022-11-08T10:37:36.441861665Z 2022-11-08 10:37:36: Post-process tables
2022-11-08T10:47:04.151236047Z Traceback (most recent call last):
2022-11-08T10:47:04.152434186Z   File "/usr/local/bin/nominatim", line 14, in <module>
2022-11-08T10:47:04.159169428Z     exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
2022-11-08T10:47:04.159240695Z   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
2022-11-08T10:47:04.160085515Z     return parser.run(**kwargs)
2022-11-08T10:47:04.160105521Z   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
2022-11-08T10:47:04.160448096Z     return args.command.run(args)
2022-11-08T10:47:04.160459744Z   File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 134, in run
2022-11-08T10:47:04.162904867Z     database_import.create_search_indices(conn, args.config,
2022-11-08T10:47:04.163038291Z   File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 246, in create_s                                                                       earch_indices
2022-11-08T10:47:04.163048077Z     sql.run_sql_file(conn, 'indices.sql', drop=drop)
2022-11-08T10:47:04.163055008Z   File "/usr/local/lib/nominatim/lib-python/nominatim/db/sql_preprocessor.py", line 97, in run_sql_fil                                                                       e
2022-11-08T10:47:04.164211920Z     cur.execute(sql)
2022-11-08T10:47:04.164229955Z   File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 36, in execute
2022-11-08T10:47:04.164762537Z     super().execute(query, args)
2022-11-08T10:47:04.164783770Z   File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
2022-11-08T10:47:04.166479210Z     return super().execute(query, vars)
2022-11-08T10:47:04.166522993Z psycopg2.OperationalError: server closed the connection unexpectedly
2022-11-08T10:47:04.166532473Z  This probably means the server terminated abnormally
2022-11-08T10:47:04.166537341Z  before or while processing the request.

**Comment by leonardehrenfried** [comment]
It would help if you post the full command line you used.

**Comment by leonardehrenfried** [comment]
I'm going to close this.

If you can provide more details you can reopen.
