### ISSUE TITLE
OSM-Nominatim import error

### ISSUE THREAD

**Issue by devopsnot** [mediagis/nominatim-docker#432]
I'm trying to import Nominatim to an external database, but I'm getting the following error.

```
 2023-03-13 12:03:19: Using project directory: /nominatim
 2023-03-13 12:03:22: Creating database
 2023-03-13 12:03:25: Setting up country tables
 2023-03-13 12:03:27: Importing OSM data file
 2023-03-13 12:03:27  osm2pgsql version 1.7.1
 2023-03-13 12:03:27  Database version: 11.5
 2023-03-13 12:03:27  ERROR: stoi
 Traceback (most recent call last):
   File "/usr/local/bin/nominatim", line 14, in <module>
     exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
     return parser.run(**kwargs)
   File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
     return args.command.run(args)
   File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 92, in run
     database_import.import_osm_data(files,
   File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 108, in import_osm_data
     run_osm2pgsql(options)
   File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 152, in run_osm2pgsql
     subprocess.run(cmd, cwd=options.get('cwd', '.'),
   File "/usr/lib/python3.10/subprocess.py", line 524, in run
     raise CalledProcessError(retcode, process.args,
 subprocess.CalledProcessError: Command '['/usr/local/lib/nominatim/osm2pgsql', '--hstore', '--latlon', '--slim', '--with-forward-dependencies', 'false', '--log-progress', 'true', '--number-processes', '1', '--cache', '3105', '--output', 'gazetteer', '--style', '/usr/local/etc/nominatim/import-full.style', '--create', 'data.osm.pbf']' returned non-zero exit status 1.
```

My bank machine has 32GB of RAM, 8 core processor.

The machine where I'm running the container to carry out the import has 64GB of RAM, also with an 8-core processor.

It doesn't give me any log in the database, only that a new database was created

**Comment by leonardehrenfried** [comment]
What is the exact command that you run?

**Comment by leonardehrenfried** [comment]
`stoi` is a function that tries to convert a string to and int. Are you perhaps passing in an arguments that cannot be converted to an int?

**Comment by leonardehrenfried** [comment]
I would try modifying the line with THREADS to just use a fixed value of 16.
