### ISSUE TITLE
Any other way other than ssh to get data from storage box

### ISSUE THREAD

**Issue by Shadow-shadown** [mediagis/nominatim-docker#513]
SCP='sshpass -p DMg5bmLPY7npHL2Q scp -o StrictHostKeyChecking=no u355874-sub1@u355874-sub1.your-storagebox.de'

This command in init.sh file can it be replace by some other working command as port 22 is not allowed to make a ssh connection to outside world from my internal network I tried to replace with the previous version init.sh file but it didn't work so any help would be appreciated

**Comment by mtmail** [comment]
You can download the files separately, then specify the path to them with the `IMPORT_*` settings https://github.com/mediagis/nominatim-docker/tree/master/4.3#configuration For example `IMPORT_WIKIPEDIA=/home/someuser/pre-downloaded/files/`

**Comment by Shadow-shadown** [comment]
But when I try to run the docker it tries to make a connection to the ssh so I need to modify the docker file? Or just add it in the docker environment variable?

**Comment by Shadow-shadown** [comment]
> You can download the files separately, then specify the path to them with the `IMPORT_*` settings https://github.com/mediagis/nominatim-docker/tree/master/4.3#configuration For example `IMPORT_WIKIPEDIA=/home/someuser/pre-downloaded/files/`

I'm getting this error when trying to do it 

2023-12-17 12:09:50: Initialising replication updates
2023-12-17 12:09:50: Failed to load URL: https://www.openstreetmap.org/api/0.6/node/11420726320/1
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 191, in run
    return self._init_replication(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 79, in _init_replication
    replication.init_replication(conn, base_url=args.config.REPLICATION_URL,
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/replication.py", line 41, in init_replication
    date = status.compute_database_date(conn)
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/status.py", line 50, in compute_database_date
    data = get_url(node_url)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 171, in get_url
    with urlrequest.urlopen(request) as response: # type: IO[bytes]
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)

**Comment by mtmail** [comment]
I guess port 443 is also blocked? In that case replication (data updates) won't work after the initial import. You can disable that by setting `UPDATE_MODE=none`. If you never run updates in the future then can also set `FREEZE=true`.

**Comment by leonardehrenfried** [comment]
It's not possible I'm afraid. We used to download via http but some people ran endless loops and used up all of nominatim's bandwidths so we had to migrate.

**Comment by Shadow-shadown** [comment]
Even after opening the port I'm still getting the dh key too small issue

**Comment by mtmail** [comment]
Which port did you open? Which commands did you run to open it? How did you verify it's open?

**Comment by Shadow-shadown** [comment]
To open the port I used the command 
Sudo ufw allow 443 
And to check if the port is open or not I did run the command 
Sudo ufw status verbose

**Comment by mtmail** [comment]
To test if the port is open run `curl "https://www.openstreetmap.org/api/0.6/node/11420726320/"` inside the Docker container. If that prints an error then talk to your system administrators to open the port.

**Comment by Shadow-shadown** [comment]
> To test if the port is open run `curl "https://www.openstreetmap.org/api/0.6/node/11420726320/"` inside the Docker container. If that prints an error then talk to your system administrators to open the port.

Thank you so much for you help really appreciate it
