### ISSUE TITLE
North America import fails

### ISSUE THREAD

**Issue by alterEgo123** [mediagis/nominatim-docker#519]
Hello,
I'm trying to deploy nominatim on AWS using the Helm chart but I keep getting this error

Defaulted container "nominatim" out of: nominatim, wait-for-db (init), download-pbf (init)
2024-01-10 15:42:28: Using project directory: /nominatim
2024-01-10 15:42:29: Creating database
2024-01-10 15:42:30: Setting up country tables
2024-01-10 15:42:32: Importing OSM data file
2024-01-10 15:42:32  osm2pgsql version 1.9.2
2024-01-10 15:42:32  Database version: 15.2
2024-01-10 15:42:32  PostGIS version: 3.3
2024-01-10 15:42:32  Storing properties to table '"public"."osm2pgsql_properties"'.
2024-01-10 17:32:40  Reading input files done in 6608s (1h 50m 8s).                       
2024-01-10 17:32:40    Processed 1821108675 nodes in 719s (11m 59s) - 2533k/s
2024-01-10 17:32:40    Processed 162164552 ways in 4778s (1h 19m 38s) - 34k/s
2024-01-10 17:32:40    Processed 1692584 relations in 1111s (18m 31s) - 2k/s
2024-01-10 17:32:40  No marked ways (Skipping stage 2).
2024-01-10 17:32:40  Clustering table 'place' by geometry...
2024-01-10 17:33:21  Done postprocessing on table 'planet_osm_nodes' in 0s
2024-01-10 17:33:21  Building index on table 'planet_osm_ways'
2024-01-10 17:51:12  Building index on table 'planet_osm_rels'
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 12, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 225, in nominatim
    return get_set_parser().run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 121, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 94, in run
    database_import.import_osm_data(files,
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 113, in import_osm_data
    run_osm2pgsql(options)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 76, in run_osm2pgsql
    subprocess.run(cmd, cwd=options.get('cwd', '.'),
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/lib/nominatim/osm2pgsql', '--hstore', '--latlon', '--slim', '--log-progress', 'true', '--number-processes', '1', '--cache', '0', '--style', '/usr/local/etc/nominatim/import-full.lua', '--output', 'flex', '--create', '--flat-nodes', '/nominatim/flatnode/flatnode.file', 'data.osm.pbf']' died with <Signals.SIGSEGV: 11>.

I'm reserving a 60GB RAM and 5 vCPU for the pod, and my database is in RDS with 2GB of RAM and 500GB of disk space.
How can I fix this?

**Comment by leonardehrenfried** [comment]
I believe it has to do with not enough ram or disk. I've added a tag and you can check other issues with the same one: https://github.com/mediagis/nominatim-docker/issues?q=label%3A%22resource+problem%22+

They might contain a clue about your problem.
